Handle invalid URIs in store_location_for
When someone inputs an invalid URI, such as, http:google.com the URI
parsing is unable to determine a path. That will cause
`remove_domain_from_uri` to throw an error:
NoMethodError: undefined method `sub' for nil:NilClass

So ensure the URI object is able to determine a path before attempting
to call `remove_domain_from_uri`.